const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcrypt');

// Load env vars
dotenv.config({ path: '../.env' }); // Assuming run from server dir

const User = require('../models/User');
const Job = require('../models/Job');
const Application = require('../models/Application');

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/mini-job-portal');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const seedData = async () => {
  try {
    await connectDB();

    console.log('Clearing existing mock data...');
    // Only delete mock data to preserve real users if any?
    // Let's clear everything for a fresh start.
    await User.deleteMany();
    await Job.deleteMany();
    await Application.deleteMany();

    console.log('Generating Mock Recruiters...');
    const salt = await bcrypt.genSalt(10);
    const password = await bcrypt.hash('123456', salt);

    const recruiters = await User.insertMany([
      { name: 'TechCorp HR', email: 'hr@techcorp.com', password, role: 'recruiter', isVerified: true },
      { name: 'Global Solutions HR', email: 'hr@globalsolutions.com', password, role: 'recruiter', isVerified: true },
      { name: 'Startup Inc HR', email: 'hr@startupinc.com', password, role: 'recruiter', isVerified: true },
    ]);

    console.log('Generating Mock Candidates...');
    const candidates = await User.insertMany([
      { name: 'Alice Smith', email: 'alice@example.com', password, role: 'candidate', isVerified: true, skills: ['React', 'Node.js'], resumeFile: 'dummy-resume.pdf' },
      { name: 'Bob Jones', email: 'bob@example.com', password, role: 'candidate', isVerified: true, skills: ['Python', 'Django'], resumeFile: 'dummy-resume.pdf' },
      { name: 'Charlie Brown', email: 'charlie@example.com', password, role: 'candidate', isVerified: true, skills: ['Java', 'Spring'], resumeFile: 'dummy-resume.pdf' },
      { name: 'Diana Prince', email: 'diana@example.com', password, role: 'candidate', isVerified: true, skills: ['AWS', 'DevOps'], resumeFile: 'dummy-resume.pdf' },
      { name: 'Evan Wright', email: 'evan@example.com', password, role: 'candidate', isVerified: true, skills: ['UX/UI', 'Figma'], resumeFile: 'dummy-resume.pdf' },
    ]);

    console.log('Generating 50+ Mock Jobs...');
    const jobTypes = ['Full-time', 'Part-time', 'Remote', 'Internship'];
    const jobTitles = ['Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Engineer', 'Data Scientist', 'DevOps Engineer', 'Product Manager', 'UX Designer', 'QA Engineer', 'Mobile Developer'];
    const locations = ['New York, NY', 'San Francisco, CA', 'London, UK', 'Berlin, Germany', 'Austin, TX', 'Remote', 'Toronto, ON', 'Sydney, AUS'];
    const companies = ['TechCorp', 'Global Solutions', 'Startup Inc', 'Innovatech', 'NextGen AI', 'CloudWorks', 'DataDriven', 'FinTech Dynamics', 'HealthTech', 'EduPlatform'];
    
    const mockJobs = [];
    for (let i = 0; i < 55; i++) {
      const recruiter = recruiters[i % recruiters.length];
      const type = jobTypes[i % jobTypes.length];
      const title = jobTitles[Math.floor(Math.random() * jobTitles.length)];
      const location = type === 'Remote' ? 'Remote' : locations[Math.floor(Math.random() * locations.length)];
      const company = companies[Math.floor(Math.random() * companies.length)];
      
      const startDate = new Date(Date.now() - Math.floor(Math.random() * 15) * 24 * 60 * 60 * 1000); // Between now and 15 days ago
      // 20% chance the job is expired, 80% chance it's still open
      const isExpired = Math.random() < 0.2;
      const endDate = new Date(startDate.getTime() + (isExpired ? 
          Math.floor(Math.random() * 5) * 24 * 60 * 60 * 1000 : 
          Math.floor(Math.random() * 30 + 5) * 24 * 60 * 60 * 1000));

      mockJobs.push({
        title: `${title} - Level ${Math.floor(Math.random() * 4) + 1}`,
        company,
        location,
        type,
        salary: `$${Math.floor(Math.random() * 80) + 60},000 - $${Math.floor(Math.random() * 80) + 120},000`,
        description: 'This is a mock job description generated by the seeding script. We are looking for highly motivated individuals to join our team.',
        recruiterId: recruiter._id,
        status: 'Active',
        applicationStartDate: startDate,
        applicationEndDate: endDate
      });
    }

    const insertedJobs = await Job.insertMany(mockJobs);

    console.log('Generating Mock Applications...');
    const mockApps = [];
    
    // Each candidate applies to 4-8 jobs
    for (const candidate of candidates) {
      const numApps = Math.floor(Math.random() * 5) + 4;
      const appliedJobIds = new Set();
      
      for (let i = 0; i < numApps; i++) {
        // Pick random job
        let randomJob;
        do {
          randomJob = insertedJobs[Math.floor(Math.random() * insertedJobs.length)];
        } while (appliedJobIds.has(randomJob._id.toString()));
        
        appliedJobIds.add(randomJob._id.toString());
        
        const statuses = ['Applied', 'Shortlisted', 'Interview Call Received', 'Selection Confirmed', 'Rejected'];
        const status = statuses[Math.floor(Math.random() * statuses.length)];

        // Create application
        const app = new Application({
          jobId: randomJob._id,
          name: candidate.name,
          email: candidate.email,
          phone: '555-0100',
          candidateId: candidate._id,
          resumePath: candidate.resumeFile,
          status,
          appliedAt: new Date(Date.now() - Math.floor(Math.random() * 10000000000))
        });
        
        mockApps.push(app);
        
        // Push to candidate's appliedJobs
        candidate.appliedJobs.push({
          applicationId: app._id,
          jobId: randomJob._id,
          title: randomJob.title,
          companyName: randomJob.company,
          status,
          appliedAt: app.appliedAt
        });
      }
      await candidate.save();
    }
    
    await Application.insertMany(mockApps);

    console.log('[DATABASE POPULATED: Mock Recruiters, Candidates, 50+ Jobs, and Applications Loaded!]');
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedData();
