const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config({ path: '../.env' }); // Assuming run from server dir

const User = require('../models/User');
const Job = require('../models/Job');
const Application = require('../models/Application');

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/mini-job-portal');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const seedNewRecruiters = async () => {
  try {
    await connectDB();

    console.log('Checking for recruiters with 0 jobs...');
    
    const recruiters = await User.find({ role: 'recruiter' });
    const candidates = await User.find({ role: 'candidate' });

    if (candidates.length === 0) {
      console.log('No candidates found in database. Cannot create mock applications.');
      process.exit();
    }

    const jobTypes = ['Full-time', 'Part-time', 'Remote', 'Internship'];
    const jobTitles = ['Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Engineer', 'Product Manager'];
    const locations = ['New York, NY', 'San Francisco, CA', 'London, UK', 'Remote'];

    for (const recruiter of recruiters) {
      const count = await Job.countDocuments({ recruiterId: recruiter._id });
      
      if (count === 0) {
        console.log(`\nFound new recruiter with no jobs: ${recruiter.email}`);
        console.log(`Generating 5 mock jobs and mock applicants for ${recruiter.name}...`);
        
        const mockJobs = [];
        for (let i = 0; i < 5; i++) {
          const type = jobTypes[i % jobTypes.length];
          const title = jobTitles[i];
          const location = type === 'Remote' ? 'Remote' : locations[i % locations.length];
          
          const startDate = new Date(Date.now() - Math.floor(Math.random() * 5) * 24 * 60 * 60 * 1000);
          const endDate = new Date(startDate.getTime() + Math.floor(Math.random() * 30 + 10) * 24 * 60 * 60 * 1000);

          mockJobs.push({
            title: `${title} - Level ${Math.floor(Math.random() * 4) + 1}`,
            company: recruiter.name || 'Custom Company',
            location,
            type,
            salary: `$${Math.floor(Math.random() * 80) + 60},000 - $${Math.floor(Math.random() * 80) + 120},000`,
            description: 'This is a mock job description generated by the seeding script. We are looking for highly motivated individuals to join our team.',
            recruiterId: recruiter._id,
            status: 'Active',
            applicationStartDate: startDate,
            applicationEndDate: endDate
          });
        }

        const insertedJobs = await Job.insertMany(mockJobs);
        console.log(`Created 5 jobs for ${recruiter.email}.`);

        // Generate applications
        const mockApps = [];
        const statuses = ['Applied', 'Shortlisted', 'Interview Call Received', 'Selection Confirmed', 'Rejected'];

        for (const job of insertedJobs) {
          // Add 2-4 mock applicants per job
          const numApplicants = Math.floor(Math.random() * 3) + 2;
          
          // shuffle candidates
          const shuffledCandidates = [...candidates].sort(() => 0.5 - Math.random());
          const selectedCandidates = shuffledCandidates.slice(0, numApplicants);

          for (const candidate of selectedCandidates) {
            const status = statuses[Math.floor(Math.random() * statuses.length)];
            
            const app = new Application({
              jobId: job._id,
              name: candidate.name,
              email: candidate.email,
              phone: '555-0100',
              candidateId: candidate._id,
              resumePath: candidate.resumeFile || 'dummy-resume.pdf',
              status,
              appliedAt: new Date(Date.now() - Math.floor(Math.random() * 10000000000))
            });
            mockApps.push(app);

            candidate.appliedJobs.push({
              applicationId: app._id,
              jobId: job._id,
              title: job.title,
              companyName: job.company,
              status,
              appliedAt: app.appliedAt
            });
            await candidate.save();
          }
        }
        
        await Application.insertMany(mockApps);
        console.log(`Loaded ${mockApps.length} mock applications into ${recruiter.email}'s dashboard!`);
      }
    }

    console.log('\n[SUCCESS] New recruiters have been populated with mock data.');
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedNewRecruiters();
